postgresql: &postgresql
  adapter: postgresql
  host: localhost
  pool: 5
  timeout: 5000
  username: jordan

development:
  <<: *postgresql
  database: app_develpment

test:
  <<: *postgresql
  database: app_test

production:
  <<: *postgresql
  database: app_production
